Write-Host '
CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Alias           Attach-DbaDatabase                                 0.9.29     dbatools
Alias           Copy-SqlAgentCategory                              0.9.29     dbatools
Alias           Copy-SqlAlert                                      0.9.29     dbatools
Alias           Copy-SqlAudit                                      0.9.29     dbatools
Alias           Copy-SqlAuditSpecification                         0.9.29     dbatools
Alias           Copy-SqlBackupDevice                               0.9.29     dbatools
Alias           Copy-SqlCentralManagementServer                    0.9.29     dbatools
Alias           Copy-SqlCredential                                 0.9.29     dbatools
Alias           Copy-SqlCustomError                                0.9.29     dbatools
Alias           Copy-SqlDatabase                                   0.9.29     dbatools
Alias           Copy-SqlDatabaseAssembly                           0.9.29     dbatools
Alias           Copy-SqlDatabaseMail                               0.9.29     dbatools
Alias           Copy-SqlDataCollector                              0.9.29     dbatools
Alias           Copy-SqlEndpoint                                   0.9.29     dbatools
Alias           Copy-SqlExtendedEvent                              0.9.29     dbatools
Alias           Copy-SqlJob                                        0.9.29     dbatools
Alias           Copy-SqlJobServer                                  0.9.29     dbatools
Alias           Copy-SqlLinkedServer                               0.9.29     dbatools
Alias           Copy-SqlLogin                                      0.9.29     dbatools
Alias           Copy-SqlOperator                                   0.9.29     dbatools
Alias           Copy-SqlPolicyManagement                           0.9.29     dbatools
Alias           Copy-SqlProxyAccount                               0.9.29     dbatools
Alias           Copy-SqlResourceGovernor                           0.9.29     dbatools
Alias           Copy-SqlServerAgent                                0.9.29     dbatools
Alias           Copy-SqlServerRole                                 0.9.29     dbatools
Alias           Copy-SqlServerTrigger                              0.9.29     dbatools
Alias           Copy-SqlSharedSchedule                             0.9.29     dbatools
Alias           Copy-SqlSpConfigure                                0.9.29     dbatools
Alias           Copy-SqlSsisCatalog                                0.9.29     dbatools
Alias           Copy-SqlSysDbUserObjects                           0.9.29     dbatools
Alias           Copy-SqlUserDefinedMessage                         0.9.29     dbatools
Alias           Detach-DbaDatabase                                 0.9.29     dbatools
Alias           Expand-SqlTLogResponsibly                          0.9.29     dbatools
Alias           Export-SqlLogin                                    0.9.29     dbatools
Alias           Export-SqlSpConfigure                              0.9.29     dbatools
Alias           Export-SqlUser                                     0.9.29     dbatools
Alias           Find-SqlDuplicateIndex                             0.9.29     dbatools
Alias           Find-SqlUnusedIndex                                0.9.29     dbatools
Alias           Get-DbaDatabaseFreeSpace                           0.9.29     dbatools
Alias           Get-DbaQueryStoreConfig                            0.9.29     dbatools
Alias           Get-DiskSpace                                      0.9.29     dbatools
Alias           Get-SqlMaxMemory                                   0.9.29     dbatools
Alias           Get-SqlRegisteredServerName                        0.9.29     dbatools
Alias           Get-SqlServerKey                                   0.9.29     dbatools
Alias           Import-SqlSpConfigure                              0.9.29     dbatools
Alias           Install-SqlWhoIsActive                             0.9.29     dbatools
Alias           Invoke-DbaSqlcmd                                   0.9.29     dbatools
Alias           Remove-SqlDatabaseSafely                           0.9.29     dbatools
Alias           Remove-SqlOrphanUser                               0.9.29     dbatools
Alias           Repair-SqlOrphanUser                               0.9.29     dbatools
Alias           Reset-SqlAdmin                                     0.9.29     dbatools
Alias           Reset-SqlSaPassword                                0.9.29     dbatools
Alias           Restore-HallengrenBackup                           0.9.29     dbatools
Alias           Restore-SqlBackupFromDirectory                     0.9.29     dbatools
Alias           Set-DbaQueryStoreConfig                            0.9.29     dbatools
Alias           Set-SqlMaxMemory                                   0.9.29     dbatools
Alias           Set-SqlTempDbConfiguration                         0.9.29     dbatools
Alias           Show-SqlDatabaseList                               0.9.29     dbatools
Alias           Show-SqlMigrationConstraint                        0.9.29     dbatools
Alias           Show-SqlServerFileSystem                           0.9.29     dbatools
Alias           Show-SqlWhoIsActive                                0.9.29     dbatools
Alias           Start-SqlMigration                                 0.9.29     dbatools
Alias           Sync-SqlLoginPermissions                           0.9.29     dbatools
Alias           Test-SqlConnection                                 0.9.29     dbatools
Alias           Test-SqlDiskAllocation                             0.9.29     dbatools
Alias           Test-SqlMigrationConstraint                        0.9.29     dbatools
Alias           Test-SqlNetworkLatency                             0.9.29     dbatools
Alias           Test-SqlPath                                       0.9.29     dbatools
Alias           Test-SqlTempDbConfiguration                        0.9.29     dbatools
Alias           Watch-SqlDbLogin                                   0.9.29     dbatools
Function        Add-DbaComputerCertificate                         0.9.29     dbatools
Function        Backup-DbaDatabase                                 0.9.29     dbatools
Function        Backup-DbaDatabaseCertificate                      0.9.29     dbatools
Function        Backup-DbaDatabaseMasterKey                        0.9.29     dbatools
Function        Clear-DbaSqlConnectionPool                         0.9.29     dbatools
Function        Connect-DbaSqlServer                               0.9.29     dbatools
Function        Copy-DbaAgentAlert                                 0.9.29     dbatools
Function        Copy-DbaAgentCategory                              0.9.29     dbatools
Function        Copy-DbaAgentJob                                   0.9.29     dbatools
Function        Copy-DbaAgentOperator                              0.9.29     dbatools
Function        Copy-DbaAgentProxyAccount                          0.9.29     dbatools
Function        Copy-DbaAgentSharedSchedule                        0.9.29     dbatools
Function        Copy-DbaBackupDevice                               0.9.29     dbatools
Function        Copy-DbaCentralManagementServer                    0.9.29     dbatools
Function        Copy-DbaCredential                                 0.9.29     dbatools
Function        Copy-DbaCustomError                                0.9.29     dbatools
Function        Copy-DbaDatabase                                   0.9.29     dbatools
Function        Copy-DbaDatabaseAssembly                           0.9.29     dbatools
Function        Copy-DbaDatabaseMail                               0.9.29     dbatools
Function        Copy-DbaEndpoint                                   0.9.29     dbatools
Function        Copy-DbaExtendedEvent                              0.9.29     dbatools
Function        Copy-DbaLinkedServer                               0.9.29     dbatools
Function        Copy-DbaLogin                                      0.9.29     dbatools
Function        Copy-DbaQueryStoreConfig                           0.9.29     dbatools
Function        Copy-DbaResourceGovernor                           0.9.29     dbatools
Function        Copy-DbaServerAudit                                0.9.29     dbatools
Function        Copy-DbaServerAuditSpecification                   0.9.29     dbatools
Function        Copy-DbaServerTrigger                              0.9.29     dbatools
Function        Copy-DbaSpConfigure                                0.9.29     dbatools
Function        Copy-DbaSqlDataCollector                           0.9.29     dbatools
Function        Copy-DbaSqlPolicyManagement                        0.9.29     dbatools
Function        Copy-DbaSqlServerAgent                             0.9.29     dbatools
Function        Copy-DbaSsisCatalog                                0.9.29     dbatools
Function        Copy-DbaSysDbUserObject                            0.9.29     dbatools
Function        Disable-DbaForceNetworkEncryption                  0.9.29     dbatools
Function        Dismount-DbaDatabase                               0.9.29     dbatools
Function        Enable-DbaForceNetworkEncryption                   0.9.29     dbatools
Function        Expand-DbaTLogResponsibly                          0.9.29     dbatools
Function        Export-DbaAvailabilityGroup                        0.9.29     dbatools
Function        Export-DbaDiagnosticQuery                          0.9.29     dbatools
Function        Export-DbaExecutionPlan                            0.9.29     dbatools
Function        Export-DbaLogin                                    0.9.29     dbatools
Function        Export-DbaScript                                   0.9.29     dbatools
Function        Export-DbaSpConfigure                              0.9.29     dbatools
Function        Export-DbaUser                                     0.9.29     dbatools
Function        Find-DbaAgentJob                                   0.9.29     dbatools
Function        Find-DbaCommand                                    0.9.29     dbatools
Function        Find-DbaDatabase                                   0.9.29     dbatools
Function        Find-DbaDatabaseGrowthEvent                        0.9.29     dbatools
Function        Find-DbaDuplicateIndex                             0.9.29     dbatools
Function        Find-DbaLoginInGroup                               0.9.29     dbatools
Function        Find-DbaOrphanedFile                               0.9.29     dbatools
Function        Find-DbaStoredProcedure                            0.9.29     dbatools
Function        Find-DbaTrigger                                    0.9.29     dbatools
Function        Find-DbaUnusedIndex                                0.9.29     dbatools
Function        Find-DbaUserObject                                 0.9.29     dbatools
Function        Find-DbaView                                       0.9.29     dbatools
Function        Get-DbaAgDatabase                                  0.9.29     dbatools
Function        Get-DbaAgentAlert                                  0.9.29     dbatools
Function        Get-DbaAgentJob                                    0.9.29     dbatools
Function        Get-DbaAgentJobHistory                             0.9.29     dbatools
Function        Get-DbaAgentJobOutputFile                          0.9.29     dbatools
Function        Get-DbaAgentLog                                    0.9.29     dbatools
Function        Get-DbaAgentOperator                               0.9.29     dbatools
Function        Get-DbaAgentSchedule                               0.9.29     dbatools
Function        Get-DbaAgReplica                                   0.9.29     dbatools
Function        Get-DbaAvailabilityGroup                           0.9.29     dbatools
Function        Get-DbaBackupDevice                                0.9.29     dbatools
Function        Get-DbaBackupHistory                               0.9.29     dbatools
Function        Get-DbaClientProtocol                              0.9.29     dbatools
Function        Get-DbaClusterActiveNode                           0.9.29     dbatools
Function        Get-DbaCmConnection                                0.9.29     dbatools
Function        Get-DbaCmObject                                    0.9.29     dbatools
Function        Get-DbaComputerCertificate                         0.9.29     dbatools
Function        Get-DbaComputerSystem                              0.9.29     dbatools
Function        Get-DbaConfig                                      0.9.29     dbatools
Function        Get-DbaConfigValue                                 0.9.29     dbatools
Function        Get-DbaCredential                                  0.9.29     dbatools
Function        Get-DbaCustomError                                 0.9.29     dbatools
Function        Get-DbaDatabase                                    0.9.29     dbatools
Function        Get-DbaDatabaseAssembly                            0.9.29     dbatools
Function        Get-DbaDatabaseCertificate                         0.9.29     dbatools
Function        Get-DbaDatabaseEncryption                          0.9.29     dbatools
Function        Get-DbaDatabaseFile                                0.9.29     dbatools
Function        Get-DbaDatabaseMasterKey                           0.9.29     dbatools
Function        Get-DbaDatabasePartitionFunction                   0.9.29     dbatools
Function        Get-DbaDatabasePartitionScheme                     0.9.29     dbatools
Function        Get-DbaDatabaseSnapshot                            0.9.29     dbatools
Function        Get-DbaDatabaseSpace                               0.9.29     dbatools
Function        Get-DbaDatabaseState                               0.9.29     dbatools
Function        Get-DbaDatabaseUdf                                 0.9.29     dbatools
Function        Get-DbaDatabaseUser                                0.9.29     dbatools
Function        Get-DbaDatabaseView                                0.9.29     dbatools
Function        Get-DbaDbMailHistory                               0.9.29     dbatools
Function        Get-DbaDbMailLog                                   0.9.29     dbatools
Function        Get-DbaDbQueryStoreOptions                         0.9.29     dbatools
Function        Get-DbaDbStoredProcedure                           0.9.29     dbatools
Function        Get-DbaDefaultPath                                 0.9.29     dbatools
Function        Get-DbaDependency                                  0.9.29     dbatools
Function        Get-DbaDetachedDatabaseInfo                        0.9.29     dbatools
Function        Get-DbaDiskSpace                                   0.9.29     dbatools
Function        Get-DbaEndpoint                                    0.9.29     dbatools
Function        Get-DbaEstimatedCompletionTime                     0.9.29     dbatools
Function        Get-DbaExecutionPlan                               0.9.29     dbatools
Function        Get-DbaFile                                        0.9.29     dbatools
Function        Get-DbaForceNetworkEncryption                      0.9.29     dbatools
Function        Get-DbaHelpIndex                                   0.9.29     dbatools
Function        Get-DbaJobCategory                                 0.9.29     dbatools
Function        Get-DbaLastBackup                                  0.9.29     dbatools
Function        Get-DbaLastGoodCheckDb                             0.9.29     dbatools
Function        Get-DbaLinkedServer                                0.9.29     dbatools
Function        Get-DbaLocaleSetting                               0.9.29     dbatools
Function        Get-DbaLogin                                       0.9.29     dbatools
Function        Get-DbaMaintenanceSolutionLog                      0.9.29     dbatools
Function        Get-DbaMaxMemory                                   0.9.29     dbatools
Function        Get-DbaMemoryUsage                                 0.9.29     dbatools
Function        Get-DbaMsdtc                                       0.9.29     dbatools
Function        Get-DbaNetworkActivity                             0.9.29     dbatools
Function        Get-DbaNetworkCertificate                          0.9.29     dbatools
Function        Get-DbaOperatingSystem                             0.9.29     dbatools
Function        Get-DbaPageFileSetting                             0.9.29     dbatools
Function        Get-DbaPermission                                  0.9.29     dbatools
Function        Get-DbaPrivilege                                   0.9.29     dbatools
Function        Get-DbaProcess                                     0.9.29     dbatools
Function        Get-DbaQueryExecutionTime                          0.9.29     dbatools
Function        Get-DbaRegisteredServerName                        0.9.29     dbatools
Function        Get-DbaRegisteredServersStore                      0.9.29     dbatools
Function        Get-DbaRestoreHistory                              0.9.29     dbatools
Function        Get-DbaRoleMember                                  0.9.29     dbatools
Function        Get-DbaRunningJob                                  0.9.29     dbatools
Function        Get-DbaSchemaChangeHistory                         0.9.29     dbatools
Function        Get-DbaServerAudit                                 0.9.29     dbatools
Function        Get-DbaServerAuditSpecification                    0.9.29     dbatools
Function        Get-DbaServerInstallDate                           0.9.29     dbatools
Function        Get-DbaServerProtocol                              0.9.29     dbatools
Function        Get-DbaSpConfigure                                 0.9.29     dbatools
Function        Get-DbaSpn                                         0.9.29     dbatools
Function        Get-DbaSqlBuildReference                           0.9.29     dbatools
Function        Get-DbaSqlInstanceProperty                         0.9.29     dbatools
Function        Get-DbaSqlInstanceUserOption                       0.9.29     dbatools
Function        Get-DbaSqlLog                                      0.9.29     dbatools
Function        Get-DbaSqlManagementObject                         0.9.29     dbatools
Function        Get-DbaSqlModule                                   0.9.29     dbatools
Function        Get-DbaSqlProductKey                               0.9.29     dbatools
Function        Get-DbaSqlService                                  0.9.29     dbatools
Function        Get-DbaSsisEnvironmentVariable                     0.9.29     dbatools
Function        Get-DbaStartupParameter                            0.9.29     dbatools
Function        Get-DbaTable                                       0.9.29     dbatools
Function        Get-DbaTcpPort                                     0.9.29     dbatools
Function        Get-DbaTempdbUsage                                 0.9.29     dbatools
Function        Get-DbatoolsLog                                    0.9.29     dbatools
Function        Get-DbaTraceFlag                                   0.9.29     dbatools
Function        Get-DbaTrigger                                     0.9.29     dbatools
Function        Get-DbaUptime                                      0.9.29     dbatools
Function        Get-DbaWindowsLog                                  0.9.29     dbatools
Function        Get-DbaXEventsSession                              0.9.29     dbatools
Function        Import-DbaCsvToSql                                 0.9.29     dbatools
Function        Import-DbaSpConfigure                              0.9.29     dbatools
Function        Install-DbaFirstResponderKit                       0.9.29     dbatools
Function        Install-DbaMaintenanceSolution                     0.9.29     dbatools
Function        Install-DbaWatchUpdate                             0.9.29     dbatools
Function        Install-DbaWhoIsActive                             0.9.29     dbatools
Function        Invoke-DbaDatabaseShrink                           0.9.29     dbatools
Function        Invoke-DbaDatabaseUpgrade                          0.9.29     dbatools
Function        Invoke-DbaDiagnosticQuery                          0.9.29     dbatools
Function        Invoke-DbaLogShipping                              0.9.29     dbatools
Function        Invoke-DbaLogShippingRecovery                      0.9.29     dbatools
Function        Invoke-DbaWhoisActive                              0.9.29     dbatools
Function        Invoke-Sqlcmd2                                     0.9.29     dbatools
Function        Measure-DbaBackupThroughput                        0.9.29     dbatools
Function        Mount-DbaDatabase                                  0.9.29     dbatools
Function        New-DbaAgentJob                                    0.9.29     dbatools
Function        New-DbaAgentJobStep                                0.9.29     dbatools
Function        New-DbaAgentSchedule                               0.9.29     dbatools
Function        New-DbaCmConnection                                0.9.29     dbatools
Function        New-DbaComputerCertificate                         0.9.29     dbatools
Function        New-DbaCredential                                  0.9.29     dbatools
Function        New-DbaDatabaseCertificate                         0.9.29     dbatools
Function        New-DbaDatabaseMasterKey                           0.9.29     dbatools
Function        New-DbaDatabaseSnapshot                            0.9.29     dbatools
Function        New-DbaScriptingOption                             0.9.29     dbatools
Function        New-DbaServiceMasterKey                            0.9.29     dbatools
Function        New-DbaSqlConnectionString                         0.9.29     dbatools
Function        New-DbaSqlConnectionStringBuilder                  0.9.29     dbatools
Function        New-DbaSqlDirectory                                0.9.29     dbatools
Function        New-DbaSsisCatalog                                 0.9.29     dbatools
Function        New-DbaTeppCompletionResult                        0.9.29     dbatools
Function        New-DbatoolsSupportPackage                         0.9.29     dbatools
Function        Out-DbaDataTable                                   0.9.29     dbatools
Function        Read-DbaBackupHeader                               0.9.29     dbatools
Function        Read-DbaTraceFile                                  0.9.29     dbatools
Function        Read-DbaTransactionLog                             0.9.29     dbatools
Function        Remove-DbaAgentJob                                 0.9.29     dbatools
Function        Remove-DbaAgentJobStep                             0.9.29     dbatools
Function        Remove-DbaAgentSchedule                            0.9.29     dbatools
Function        Remove-DbaBackup                                   0.9.29     dbatools
Function        Remove-DbaCmConnection                             0.9.29     dbatools
Function        Remove-DbaComputerCertificate                      0.9.29     dbatools
Function        Remove-DbaDatabase                                 0.9.29     dbatools
Function        Remove-DbaDatabaseCertificate                      0.9.29     dbatools
Function        Remove-DbaDatabaseMasterKey                        0.9.29     dbatools
Function        Remove-DbaDatabaseSafely                           0.9.29     dbatools
Function        Remove-DbaDatabaseSnapshot                         0.9.29     dbatools
Function        Remove-DbaNetworkCertificate                       0.9.29     dbatools
Function        Remove-DbaOrphanUser                               0.9.29     dbatools
Function        Remove-DbaSpn                                      0.9.29     dbatools
Function        Rename-DbaLogin                                    0.9.29     dbatools
Function        Repair-DbaOrphanUser                               0.9.29     dbatools
Function        Repair-DbaServerName                               0.9.29     dbatools
Function        Reset-DbaAdmin                                     0.9.29     dbatools
Function        Resolve-DbaNetworkName                             0.9.29     dbatools
Function        Restore-DbaBackupFromDirectory                     0.9.29     dbatools
Function        Restore-DbaDatabase                                0.9.29     dbatools
Function        Restore-DbaDatabaseCertificate                     0.9.29     dbatools
Function        Restore-DbaFromDatabaseSnapshot                    0.9.29     dbatools
Function        Save-DbaDiagnosticQueryScript                      0.9.29     dbatools
Function        Set-DbaAgentJob                                    0.9.29     dbatools
Function        Set-DbaAgentJobOutputFile                          0.9.29     dbatools
Function        Set-DbaAgentJobStep                                0.9.29     dbatools
Function        Set-DbaAgentSchedule                               0.9.29     dbatools
Function        Set-DbaCmConnection                                0.9.29     dbatools
Function        Set-DbaConfig                                      0.9.29     dbatools
Function        Set-DbaDatabaseOwner                               0.9.29     dbatools
Function        Set-DbaDatabaseState                               0.9.29     dbatools
Function        Set-DbaDbCompression                               0.9.29     dbatools
Function        Set-DbaDbQueryStoreOptions                         0.9.29     dbatools
Function        Set-DbaJobOwner                                    0.9.29     dbatools
Function        Set-DbaMaxDop                                      0.9.29     dbatools
Function        Set-DbaMaxMemory                                   0.9.29     dbatools
Function        Set-DbaNetworkCertificate                          0.9.29     dbatools
Function        Set-DbaPowerPlan                                   0.9.29     dbatools
Function        Set-DbaPrivilege                                   0.9.29     dbatools
Function        Set-DbaSpConfigure                                 0.9.29     dbatools
Function        Set-DbaSpn                                         0.9.29     dbatools
Function        Set-DbaStartupParameter                            0.9.29     dbatools
Function        Set-DbaTcpPort                                     0.9.29     dbatools
Function        Set-DbaTempDbConfiguration                         0.9.29     dbatools
Function        Show-DbaDatabaseList                               0.9.29     dbatools
Function        Show-DbaServerFileSystem                           0.9.29     dbatools
Function        Start-DbaMigration                                 0.9.29     dbatools
Function        Stop-DbaProcess                                    0.9.29     dbatools
Function        Sync-DbaSqlLoginPermission                         0.9.29     dbatools
Function        Test-DbaCmConnection                               0.9.29     dbatools
Function        Test-DbaConnection                                 0.9.29     dbatools
Function        Test-DbaConnectionAuthScheme                       0.9.29     dbatools
Function        Test-DbaDatabaseCollation                          0.9.29     dbatools
Function        Test-DbaDatabaseCompatibility                      0.9.29     dbatools
Function        Test-DbaDatabaseOwner                              0.9.29     dbatools
Function        Test-DbaDbCompression                              0.9.29     dbatools
Function        Test-DbaDiskAlignment                              0.9.29     dbatools
Function        Test-DbaDiskAllocation                             0.9.29     dbatools
Function        Test-DbaFullRecoveryModel                          0.9.29     dbatools
Function        Test-DbaIdentityUsage                              0.9.29     dbatools
Function        Test-DbaJobOwner                                   0.9.29     dbatools
Function        Test-DbaLastBackup                                 0.9.29     dbatools
Function        Test-DbaLinkedServerConnection                     0.9.29     dbatools
Function        Test-DbaMaxDop                                     0.9.29     dbatools
Function        Test-DbaMaxMemory                                  0.9.29     dbatools
Function        Test-DbaMigrationConstraint                        0.9.29     dbatools
Function        Test-DbaNetworkLatency                             0.9.29     dbatools
Function        Test-DbaOptimizeForAdHoc                           0.9.29     dbatools
Function        Test-DbaPowerPlan                                  0.9.29     dbatools
Function        Test-DbaServerName                                 0.9.29     dbatools
Function        Test-DbaSpn                                        0.9.29     dbatools
Function        Test-DbaSqlManagementObject                        0.9.29     dbatools
Function        Test-DbaSqlPath                                    0.9.29     dbatools
Function        Test-DbaTempDbConfiguration                        0.9.29     dbatools
Function        Test-DbaValidLogin                                 0.9.29     dbatools
Function        Test-DbaVirtualLogFile                             0.9.29     dbatools
Function        Uninstall-DbaWatchUpdate                           0.9.29     dbatools
Function        Update-DbaTools                                    0.9.29     dbatools
Function        Watch-DbaDbLogin                                   0.9.29     dbatools
Function        Watch-DbaUpdate                                    0.9.29     dbatools
Function        Where-DbaObject                                    0.9.29     dbatools
Function        Write-DbaDataTable                                 0.9.29     dbatools'