; Servers categorized by auto-detected role
; Generated on 09/19/2025 16:44:50

[Databases]
server=GXE-SQL1

[Kms]
server=GXE-KMS

[LogRhythm]
server=GXE-LR-PM1
server=GXE-LR-DP1
server=GXE-LR-WEB1
server=GXE-LR-AIE1
server=GXN-LR-DP2
server=GXN-LR-AIE1
server=GXN-LR-DP1
server=GXE-LR-DP2

[Sentris]
server=GXE-SEN-FE1
server=GXE-SEN-FE2
server=GXE-SEN-SQL2
server=GXE-SEN-SQL1
server=GXE-SEN-SQL-CL
server=GXN-SEN-FE1
server=GXN-SEN-FE2
server=GXN-SEN-SQL1
server=GXN-SEN-SQL2

[Citrix]
server=GXE-VDI-DDC1
server=GXE-VDI-DDC2
server=GXE-VDI-DTR1
server=GXE-VDI-DTR2
server=GXE-VDI-SF2
server=GXE-VDI-SF1
server=GXE-VDI-TZM
server=GXE-VDI-SQL1
server=GXE-VDI-SQL2

[Sca]
server=GXE-SCA

[Ps]
server=GXE-PS1
server=GXN-PS1

[Symantic]
server=GXE-SEP

[UpdateServer]
server=GXE-WSUS
server=GXN-WSUS

[Nessus]
server=GXE-IAT1
server=GXN-IAT1

[Adm]
server=GXE-ADM
server=GXN-ADM

[DHCP]
server=GXE-DHCP

[Cdp]
server=GXE-CDP
server=GXN-CDP

[DomainController]
server=GXE-DC1
server=GXE-DC2
server=GXN-DC1
server=GXN-DC2

[Xcp]
server=GXE-XCP-SRC

[FileShare]
server=GXE-FS1
server=GXE-FS2
server=GXN-FS1
server=GXN-FS2

[WindowsEventCollector]
server=GXE-WEC-APP
server=GXE-WEC-SEC
server=GXE-WEC-SEN
server=GXE-WEC-SYS

[ForcePoint]
server=GXE-FP

